(global-set-key [f5] 'ph/change-to-emacs-directory)
(global-set-key [f6] 'ph/edit-user-init-file)
(global-set-key [f8] 'ph/find-agenda-file)
(global-set-key [f7] 'ph/load-user-init-file)
(global-set-key (kbd "C-<return>") 'ph/open-line-below)
(global-set-key (kbd "C-M-<return>") 'ph/open-line-above)
